runtime: python39  # Hoặc python38, python310 tùy phiên bản bạn dùng
entrypoint: gunicorn -b :$PORT app:app  # app là tên file Flask và Flask instance

# Cấu hình xử lý các URL
handlers:
  # Xử lý tài nguyên tĩnh (CSS, JS, hình ảnh)
  - url: /static
    static_dir: static
  # Mặc định cho các URL khác
  - url: /.*
    script: auto

# Cấu hình tự động mở rộng (Scaling)
automatic_scaling:
  target_cpu_utilization: 0.65  # CPU mục tiêu để kích hoạt mở rộng
  target_throughput_utilization: 0.75  # Tỷ lệ lưu lượng mục tiêu
  max_instances: 1  # Số lượng phiên bản tối đa để kiểm soát chi phí
  min_instances: 1  # Số lượng phiên bản tối thiểu để duy trì thời gian phản hồi nhanh

# Cấu hình tài nguyên (RAM, CPU)
instance_class: F2  # Hoặc F4 cho ứng dụng yêu cầu nhiều tài nguyên hơn

# Cấu hình logging
env_variables:
  FLASK_ENV: production  # Đặt ứng dụng Flask ở chế độ sản xuất